name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  format:
    name: Run Prettier
    uses: ./.github/workflows/prettier.yml
    secrets: inherit

  typecheck:
    name: Run TypeScript
    uses: ./.github/workflows/typecheck.yml
    secrets: inherit

  lint:
    name: Run Eslint
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  build:
    name: Build app
    uses: ./.github/workflows/build.yml
    secrets: inherit

  required:
    needs: [format, typecheck, lint, build]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1
